apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: go-test-2 
  janus-idp.io/tekton: go-test-2
  backstage.io/kubernetes-id: go-test-2
  backstage.io/kubernetes-namespace: go-test-2 
  app.kubernetes.io/part-of: go-test-2
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  